{{- if .Values.stackstorm.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-mongo
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" . }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.mongo.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.mongo.size }}
  {{- include "poundcakeStackstorm.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.mongo.storageClassName) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-rabbitmq
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" . }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.rabbitmq.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.rabbitmq.size }}
  {{- include "poundcakeStackstorm.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.rabbitmq.storageClassName) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-redis
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" . }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.redis.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.redis.size }}
  {{- include "poundcakeStackstorm.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.redis.storageClassName) | nindent 2 }}
{{- if and (eq (include "poundcakeStackstorm.stackstormThirdPartyPacksEnabled" .) "true") (eq (include "poundcakeStackstorm.stackstormSharedStorageEnabled" .) "true") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-packs
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" . }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.packVolumeSize }}
  {{- include "poundcakeStackstorm.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcakeStackstorm.stackstormSharedStorageClassName" .)) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-virtualenvs
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" . }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.virtualenvVolumeSize }}
  {{- include "poundcakeStackstorm.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcakeStackstorm.stackstormSharedStorageClassName" .)) | nindent 2 }}
{{- end }}
{{- end }}
