{{- if and .Values.stackstorm.enabled .Values.stackstorm.enabled }}
{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.existingSecret) }}
{{- $secretName := include "poundcakeStackstorm.rabbitmqSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $username := .Values.rabbitmq.auth.username | default "stackstorm" }}
{{- $password := .Values.rabbitmq.auth.password | default .Values.rabbitmq.password | default "stackstorm" }}
{{- if $existingSecret }}
  {{- $existingUsername := index $existingSecret.data "username" }}
  {{- if $existingUsername }}
    {{- $username = $existingUsername | b64dec }}
  {{- end }}
  {{- $existingPassword := index $existingSecret.data "password" }}
  {{- if $existingPassword }}
    {{- $password = $existingPassword | b64dec }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
{{- end }}
{{- end }}
