{{- if .Values.stackstorm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-mongodb
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: stackstorm-mongodb
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-rabbitmq
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: stackstorm-rabbitmq
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mgmt
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-redis
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: stackstorm-redis
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-api
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.stackstormApi.type }}
  selector:
    app.kubernetes.io/component: stackstorm-api
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.stackstormApi.port }}
      targetPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-auth
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.stackstormAuth.type }}
  selector:
    app.kubernetes.io/component: stackstorm-auth
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.stackstormAuth.port }}
      targetPort: 9100
{{- if eq (include "poundcakeStackstorm.stackstormServiceEnabled" (dict "root" . "name" "stream")) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-stream
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.stackstormStream.type }}
  selector:
    app.kubernetes.io/component: stackstorm-stream
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.stackstormStream.port }}
      targetPort: 9102
{{- end }}
{{- if eq (include "poundcakeStackstorm.stackstormServiceEnabled" (dict "root" . "name" "web")) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: stackstorm-web
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.stackstormWeb.type }}
  selector:
    app.kubernetes.io/component: stackstorm-web
    {{- include "poundcakeStackstorm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.stackstormWeb.port }}
      targetPort: 8080
{{- end }}
{{- end }}
