{{- if and .Values.stackstorm.enabled .Values.pdb.enabled }}
{{- $items := list "mongodb" "rabbitmq" "redis" "api" -}}
{{- range $item := $items }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stackstorm-{{ $item }}
  namespace: {{ include "poundcakeStackstorm.stackstormNamespace" $ }}
  labels:
    {{- include "poundcakeStackstorm.labels" $ | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: stackstorm-{{ $item }}
      {{- include "poundcakeStackstorm.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
