{{- if and .Values.stackstorm.enabled .Values.stackstorm.enabled }}
{{- if and .Values.mongodb.enabled (not .Values.mongodb.external) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poundcakeStackstorm.stackstormMongoName" . }}-init
  labels:
    {{- include "poundcakeStackstorm.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
data:
  01-create-st2-user.js: |
    // Ensure StackStorm DB user exists on first Mongo bootstrap.
    db = db.getSiblingDB("{{ .Values.mongodb.auth.database }}");
    db.createUser({
      user: "{{ .Values.mongodb.auth.username }}",
      pwd: "{{ .Values.mongodb.auth.password }}",
      roles: [{ role: "dbOwner", db: "{{ .Values.mongodb.auth.database }}" }]
    });
{{- end }}
{{- end }}
